import { Inter as GeistSans } from 'next/font/google'
import { JetBrains_Mono as GeistMono } from 'next/font/google'
import './globals.css'

const geistSans = GeistSans({
  subsets: ['latin'],
})

const geistMono = GeistMono({
  subsets: ['latin'],
})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans} ${geistMono} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
